"""'migrate'

Revision ID: 15fb2ecaae24
Revises: 
Create Date: 2019-08-15 20:19:11.191214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15fb2ecaae24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=191), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=191), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=191), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('best100_1300k')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best100_1300k',
    sa.Column('Idx', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ImageURL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ItemCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Brand', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ItemName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('SalePrice', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('NumOfReview', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('NumOfLike', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('RegDate', mysql.DATETIME(), nullable=True),
    sa.Column('MatchedItem', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Idx'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
