"""'mig'

Revision ID: 257f3df6c45b
Revises: 58d87daa8513
Create Date: 2019-09-01 22:49:09.962598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '257f3df6c45b'
down_revision = '58d87daa8513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'department_id',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.alter_column('user', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user', 'job_id',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.alter_column('user', 'login_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user', 'login_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('user', 'job_id',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    op.alter_column('user', 'group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user', 'department_id',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###
