"""empty message

Revision ID: 285a8c1f0427
Revises: 15fb2ecaae24
Create Date: 2019-08-16 22:40:31.523772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285a8c1f0427'
down_revision = '15fb2ecaae24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('todo', sa.String(length=255), nullable=False),
    sa.Column('regdate', sa.DateTime(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
