"""'mig'

Revision ID: 45594fec13e6
Revises: 257f3df6c45b
Create Date: 2019-09-02 22:43:30.800598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45594fec13e6'
down_revision = '257f3df6c45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('user_job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=20), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('user_permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(length=20), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.drop_table('permission')
    op.drop_table('admin_group')
    op.drop_table('job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('job_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('job_name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('job_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('admin_group',
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('permission',
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('permission_name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('user_permission')
    op.drop_table('user_job')
    op.drop_table('user_group')
    # ### end Alembic commands ###
