"""'mig'

Revision ID: 58d87daa8513
Revises: 
Create Date: 2019-09-01 21:44:36.905591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58d87daa8513'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('group_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=20), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(length=20), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.drop_table('user_group')
    op.add_column('user', sa.Column('cell_number', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('department_id', sa.String(length=3), nullable=False))
    op.add_column('user', sa.Column('employee_no', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('gender', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('hired_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('job_id', sa.String(length=3), nullable=False))
    op.add_column('user', sa.Column('login_name', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('retire_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('user_password', sa.String(length=255), nullable=True))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=191),
               nullable=True)
    op.drop_index('email', table_name='user')
    op.drop_index('username', table_name='user')
    op.create_unique_constraint(None, 'user', ['login_name'])
    op.drop_column('user', 'username')
    op.drop_column('user', 'admin')
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'id')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=191), nullable=True))
    op.add_column('user', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('user', sa.Column('registered_on', mysql.DATETIME(), nullable=False))
    op.add_column('user', sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=191),
               nullable=False)
    op.drop_column('user', 'user_password')
    op.drop_column('user', 'update_date')
    op.drop_column('user', 'retire_date')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'name')
    op.drop_column('user', 'login_name')
    op.drop_column('user', 'job_id')
    op.drop_column('user', 'hired_date')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'employee_no')
    op.drop_column('user', 'department_id')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'create_date')
    op.drop_column('user', 'cell_number')
    op.create_table('user_group',
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('permission')
    op.drop_table('job')
    op.drop_table('group_permission')
    op.drop_table('admin_group')
    # ### end Alembic commands ###
