"""'migration'

Revision ID: 5bcb2472d91f
Revises: 285a8c1f0427
Create Date: 2019-08-27 22:05:30.335869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bcb2472d91f'
down_revision = '285a8c1f0427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group_id', sa.Integer(), nullable=False))
    op.drop_column('user', 'user_level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_level', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.drop_column('user', 'group_id')
    # ### end Alembic commands ###
