"""'migration'

Revision ID: 60eac2dbe72b
Revises: b3e341178bb6
Create Date: 2019-08-27 22:15:08.401460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60eac2dbe72b'
down_revision = 'b3e341178bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.drop_table('group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_group')
    # ### end Alembic commands ###
