"""'meneadd'

Revision ID: 8f128266eb74
Revises: f2dc8380ccff
Create Date: 2019-10-20 12:29:18.540880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f128266eb74'
down_revision = 'f2dc8380ccff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('redirect', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('no_chashe', sa.Boolean(), nullable=False),
    sa.Column('affix', sa.Boolean(), nullable=False),
    sa.Column('breadcrumb', sa.Boolean(), nullable=False),
    sa.Column('regdate', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('last_mod_user', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_menu')
    # ### end Alembic commands ###
