"""'changecol'

Revision ID: 9e3d70e7801c
Revises: cbf1033b1d9f
Create Date: 2019-11-04 00:05:42.701371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e3d70e7801c'
down_revision = 'cbf1033b1d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_menu', sa.Column('no_cache', sa.SmallInteger(), nullable=False))
    op.drop_column('admin_menu', 'no_chashe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_menu', sa.Column('no_chashe', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('admin_menu', 'no_cache')
    # ### end Alembic commands ###
