"""redirect_string

Revision ID: a5ad206ef173
Revises: ab1e5bc9e0f9
Create Date: 2019-12-17 15:19:44.196166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ad206ef173'
down_revision = 'ab1e5bc9e0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_menu', sa.Column('redirect', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_menu', 'redirect')
    # ### end Alembic commands ###
