"""reguser

Revision ID: b175fd946142
Revises: 9e3d70e7801c
Create Date: 2019-11-22 19:44:24.923864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b175fd946142'
down_revision = '9e3d70e7801c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_menu', sa.Column('reg_user', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_menu', 'reg_user')
    # ### end Alembic commands ###
