"""'addcol'

Revision ID: b5c38e2c01af
Revises: 8f128266eb74
Create Date: 2019-10-22 14:53:06.961027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c38e2c01af'
down_revision = '8f128266eb74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_menu', sa.Column('status', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_menu', 'status')
    # ### end Alembic commands ###
